2018-08-06 00:07:08,158 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:12:50,932 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:14:18,120 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:14:38,023 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:20:28,671 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:21:39,101 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:23:33,043 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:25:09,877 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:25:59,026 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-06 00:26:37,262 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-23 15:31:20,240 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-23 15:31:28,156 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:37:55,857 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:38:46,324 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:40:04,159 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:41:04,065 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:43:44,018 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:46:05,446 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:46:16,596 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:46:25,403 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 14:51:47,367 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:01:07,458 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:02:46,806 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:03:08,532 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:03:26,315 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:03:44,132 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:04:04,648 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:04:23,118 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:04:54,269 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:05:19,973 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:05:44,164 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:06:05,126 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:07:03,451 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-24 15:08:56,005 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:28]
2018-08-25 15:38:40,330 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:30]
2018-09-03 16:32:16,327 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:30]
2018-09-03 16:32:24,346 ERROR: Exception on /cut [POST] [in /Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Filip/code/python/beaver/app/routes.py", line 37, in cut
    charty = chartify ( response )
  File "/Users/Filip/code/python/beaver/app/woodcut/algorithms/greedy.py", line 43, in chartify
    if len(board.contents) > max_num_items:
AttributeError: 'Board' object has no attribute 'contents'
2018-09-03 16:35:44,140 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:30]
2018-09-03 16:41:11,746 ERROR: Exception on /cut [POST] [in /Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Filip/code/python/beaver/app/routes.py", line 37, in cut
    charty = chartify ( response )
  File "/Users/Filip/code/python/beaver/app/woodcut/algorithms/greedy.py", line 43, in chartify
    if len(board.contents) > max_num_items:
AttributeError: 'Board' object has no attribute 'contents'
2018-09-03 16:41:13,198 ERROR: Exception on /cut [POST] [in /Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Filip/code/python/beaver/app/routes.py", line 37, in cut
    charty = chartify ( response )
  File "/Users/Filip/code/python/beaver/app/woodcut/algorithms/greedy.py", line 43, in chartify
    if len(board.contents) > max_num_items:
AttributeError: 'Board' object has no attribute 'contents'
2018-09-03 16:41:39,336 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:30]
2018-09-03 16:42:05,307 ERROR: Exception on /cut [POST] [in /Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Filip/code/python/miniconda3/envs/flasklite/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Filip/code/python/beaver/app/routes.py", line 37, in cut
    charty = chartify ( response )
  File "/Users/Filip/code/python/beaver/app/woodcut/algorithms/greedy.py", line 43, in chartify
    if len(board.contents) > max_num_items:
AttributeError: 'Board' object has no attribute 'contents'
2018-09-03 16:43:01,080 INFO: Microblog startup [in /Users/Filip/code/python/beaver/app/__init__.py:30]
